# Generated by Django 4.1.1 on 2022-09-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
