# Generated by Django 4.1.1 on 2022-09-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_food_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
