# Generated by Django 4.1.1 on 2022-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_restaurant_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
